// Interface copy only. Imported jobs, facts and CV text are never translated here.
window.WorkbenchChinese = {
  "Read from a public webpage. Check the description below for completeness; the source and whether the role is still open have not been verified.": "已从公开网页提取。请核对下方职位正文是否完整；来源真实性及岗位是否仍开放尚未核验。",
  "Paste a job posting URL": "粘贴单条岗位的 URL",
  "Read and generate": "读取并生成",
  "Job posting URL": "岗位链接",
  "Enter any public job posting URL. If the site blocks reading or the description is incomplete, paste it manually below.": "可输入任意公开岗位链接。如果网站限制读取或正文不完整，可在下方手动粘贴。",
  "Reading and preparing…": "正在读取并准备草稿…",
  "This job is already saved. Opened its existing version.": "这个岗位已保存，已打开现有版本。",
  "Paste a job link to read its description and prepare a CV draft for review.": "粘贴岗位链接，自动读取职位描述并准备待审核的简历草稿。",
  "Paste the description manually": "手动粘贴职位描述",
  "Save Chinese CV": "保存中文简历",
  "Save English CV": "保存英文简历",
  "Saving updates only this CV language. The other language stays available; earlier versions are kept in history.": "只更新当前选择的语言版本，另一语言的简历继续保留；旧版本保存在历史记录中。",
  "CV upload language": "上传简历的语言",
  "Available CVs: ": "已保存简历：",
  "Upload a Chinese or English PDF to begin.": "上传中文或英文 PDF 简历开始使用。",
  "Fact text": "经历内容",
  "Skill tags": "技能标签（逗号分隔）",
  "Edit this line": "修改这条内容",
  "Saving creates a new version pending confirmation. Earlier text stays in history; affected CVs need review again.": "保存会创建待确认的新版本，原文保留在历史中；受影响的简历需要重新审核。",
  "Save changes": "保存修改",
  "Saved. Confirm the changed line before preparing the CV again.": "已保存。请先确认修改后的内容，再重新准备简历。",
  "CV language for this job": "这个岗位使用的简历语言",
  "This CV profile changed. Prepare it again and review the new version.": "简历资料已更新，请重新准备并审核新版本。",
  "Your profile or facts changed. This is an old draft. Start over and review the new version.": "简历资料或事实已更新。下方是旧稿，请重新准备并审核新版本。",
  "Tencent's public careers board is also supported: ": "也支持腾讯公开招聘官网：",
  "Job region": "岗位地区",
  "All regions": "全部地区",
  "Mainland China": "中国大陆",
  "Other regions": "其他地区",
  "Unknown region": "地区未知",
  "Feiran": "Feiran · 斐然",
  "What oft was thought, but ne’er so well express’d.": "What oft was thought, but ne’er so well express’d.",
  "Facts": "事实资料",
  "Find jobs": "发现岗位",
  "My jobs": "我的岗位",
  "Interface language": "界面语言",
  "Label, e.g. GitHub": "名称，例如 GitHub",
  "Remove": "移除",
  " · already in your facts": " · 已在事实资料中",
  "Replace my CV with this": "替换当前简历",
  "Save as my CV": "保存为我的简历",
  "1. Check your name and contact details": "1. 核对姓名和联系方式",
  "Read from the top of your CV on this computer and never sent to DeepSeek. They go on the header of every CV.": "在本机读取简历顶部的信息，不会发送给 DeepSeek。这些信息将显示在每份简历的页眉中。",
  "Name *": "姓名 *",
  "Location": "地点",
  "Phone": "电话",
  "Email": "邮箱",
  "Links": "链接",
  "Add link": "添加链接",
  "Also at the top of your CV, not used: ": "简历顶部还有以下未使用的信息：",
  "Copied word for word from your PDF. After saving, each line waits in the list below until you confirm it": "逐字复制自你的 PDF。保存后，各行会在下方列表中等待你确认",
  "Saving replaces your current CV layout; the old one is kept in profile-history.": "保存将替换当前简历结构，旧版本会保存在简历历史记录中。",
  "Cancel": "取消",
  "Your CV": "你的简历",
  "Upload your CV as a PDF: each line becomes a fact for you to confirm, and its layout is the base of every job's CV. ": "上传 PDF 简历：每一行都会成为待确认的事实，简历结构将作为各岗位简历的基础。",
  "Your name, email, phone and links stay on this computer; DeepSeek sees the other lines to tell sections, entries and bullets apart.": "姓名、邮箱、电话和链接保留在本机；DeepSeek 仅根据其余文本识别章节、经历和要点。",
  "Choose a PDF": "选择 PDF 文件",
  "Confirm selected": "确认所选事实",
  "Select all pending": "选择全部待确认事实",
  "Read each one carefully before confirming.": "确认前请逐条核对。",
  "No facts yet. Upload your CV above: each of its lines becomes a fact to confirm here.": "还没有事实资料。请在上方上传简历，各行会在这里等待确认。",
  "Fact": "事实",
  "Text and tags": "内容与标签",
  "Status": "状态",
  "Software Engineer Intern": "例如：软件工程实习生",
  "Company": "公司",
  "https://… (official posting)": "https://…（官方岗位链接）",
  "Paste the full job description here": "在此粘贴完整的岗位描述",
  "Create job": "创建岗位",
  "No jobs yet.": "还没有岗位。",
  "Job": "岗位",
  "Captured": "录入时间",
  "Progress": "进度",
  "Jobs": "岗位列表",
  "New job": "新增岗位",
  "Paste a job description from any site. Its requirements are found and your CV is prepared for it automatically.": "粘贴任意网站的岗位描述，系统会自动提取要求，并据此准备简历。",
  "Title *": "岗位名称 *",
  "Official link": "官方链接",
  "Leave empty if unknown; the source is then recorded as unknown.": "不清楚时请留空，来源将记录为未知。",
  "Job description *": "岗位描述 *",
  "never": "从未更新",
  "just now": "刚刚",
  "location unknown": "地点未知",
  "Open": "打开",
  "Start": "开始准备",
  "Loading…": "加载中…",
  "Title contains, e.g. engineer or intern": "岗位名称包含，例如 engineer 或 intern",
  "Location contains, e.g. New York or Remote": "地点包含，例如 New York 或 Remote",
  "Filter": "筛选",
  "Refresh all": "全部刷新",
  "No confirmed skills yet, so nothing can be matched. ": "还没有已确认的技能，暂时无法匹配。",
  "Confirm your facts first.": "请先确认事实资料。",
  "You are not following any company. Add one under Companies below.": "尚未关注任何公司，可在下方的公司列表中添加。",
  "Downloading jobs…": "正在获取岗位…",
  "No jobs match these filters.": "没有符合筛选条件的岗位。",
  "Your skills it mentions": "岗位提到的已有技能",
  "Showing the top 200. Use the filters to narrow the list.": "当前显示前 200 条，请使用筛选缩小范围。",
  "Paste a job board link, e.g. https://jobs.lever.co/palantir": "粘贴公司招聘页链接，例如 https://jobs.lever.co/palantir",
  "Add company": "添加公司",
  "Jobs come from each company's public job board (Greenhouse, Lever or Ashby). No login, and nothing about you is sent.": "岗位来自公司的公开招聘页（Greenhouse、Lever 或 Ashby）。无需登录，也不会发送你的个人信息。",
  "Open jobs": "在招岗位",
  "Updated": "更新时间",
  "Ranking…": "正在排序…",
  "Jobs that match your skills": "与你的技能相关的岗位",
  "Most matched first: how many of your confirmed skills each posting mentions. ": "按岗位提到的已确认技能数量排序，数量多的排在前面。",
  "It counts words; it is not a fit score or your chance of an offer. Pending facts never count.": "这里只统计关键词，不代表综合匹配度或录用概率。待确认的事实不参与计算。",
  "Hides Senior, Staff, Principal, Lead, Manager, Director… titles. \"Member of Technical Staff\" stays.": "隐藏名称含 Senior、Staff、Principal、Lead、Manager、Director 等的岗位；保留 Member of Technical Staff。",
  " Hide senior roles": " 隐藏资深及管理岗位",
  "Requirements": "岗位要求",
  "CV (EN)": "英文简历",
  "CV (ZH)": "中文简历",
  "Required": "必需",
  "Preferred (nice to have)": "优先条件（加分项）",
  "Not marked required or preferred": "未说明是必需还是优先条件",
  "added by you": "由你添加",
  "reviewed by you": "已由你审核",
  "counted automatically, not reviewed": "自动计入，尚未审核",
  " Requirement": " 是岗位要求",
  " Not a requirement": " 不是岗位要求",
  "Copy a line or phrase exactly from the job description": "从岗位描述中原样复制一句话或短语",
  "Add missed requirement": "补充遗漏的要求",
  "Added. It counts, and the CV was prepared again.": "已添加并计入要求，简历已重新准备。",
  "Save": "保存",
  "Find again with DeepSeek": "用 DeepSeek 重新提取",
  "Found by DeepSeek, which picks lines of the job description; each line is copied word for word.": "由 DeepSeek 从岗位描述中选取，各条内容均逐字复制自原文。",
  "Saving changes here prepares the CV again; an approved CV is moved to the job's history folder.": "保存这里的修改会重新准备简历；已批准的简历会移入该岗位的历史记录。",
  "No requirement lines were found. Try Find again with DeepSeek, or add lines below by copying exact text from the job description.": "未找到岗位要求。可用 DeepSeek 重新提取，或在下方粘贴岗位描述中的原文。",
  "1. What this job asks for": "1. 这个岗位有哪些要求",
  " All of them count, and your CV below is adjusted to them. If a line is not really a requirement, choose Not a requirement and Save; saving also marks the list as reviewed by you.": "以下条目均已计入要求，简历会据此调整。若某条并非要求，请选择“不是岗位要求”并保存；保存后，该列表也会标记为已由你审核。",
  "Working…": "处理中…",
  "English CV (US Letter)": "英文简历（US Letter）",
  "Chinese CV (A4)": "中文简历（A4）",
  "Redo": "重做",
  "Undo": "撤销",
  "Undone: your usual CV is shown for this part.": "已撤销：这一部分显示原简历内容。",
  "Not prepared yet.": "尚未准备。",
  "Try again": "重试",
  "Prepare this CV": "准备这份简历",
  "Reword with DeepSeek": "用 DeepSeek 润色",
  "Adjust for this job": "根据此岗位调整",
  "Adjust again": "重新调整",
  "Start over": "重新开始",
  "Create final PDF": "生成最终 PDF",
  "Download final PDF": "下载最终 PDF",
  "This is your usual CV: DeepSeek could not reword or adjust it yet. Use the buttons above.": "当前显示原简历，DeepSeek 尚未完成润色或调整。可使用上方按钮重试。",
  "Reworded, but not adjusted for this job yet: DeepSeek could not plan it. Use Adjust for this job.": "已润色，但 DeepSeek 尚未完成针对该岗位的结构调整。可点击“根据此岗位调整”。",
  "Chinese": "中文",
  "English": "英文",
  " — undo any you disagree with:": "，可撤销任何不认可的修改：",
  "DeepSeek kept your usual CV unchanged for this job.": "DeepSeek 对此岗位保留了原简历，未作修改。",
  "Approve this CV": "批准这份简历",
  " I read the CV below and every change listed above.": " 我已阅读下方简历及上方列出的每一处修改。",
  "2. Your CV for this job": "2. 为这个岗位准备的简历",
  "Made from your confirmed facts and adjusted for this job: the most relevant parts first, what does not help cut, ": "根据已确认的事实，为此岗位调整简历：相关内容优先，删减无帮助的部分，",
  "and wording that follows the job's requirements. Nothing is added, and every reworded line is fact-checked. ": "并使措辞贴合岗位要求。不新增事实，每一条改写都经过事实核查。",
  "DeepSeek sees only your CV lines and this job's requirements, never your name, contact details, schools or employers.": "DeepSeek 仅接收简历要点与岗位要求，不接收姓名、联系方式、学校或雇主名称。",
  "Add to your skills line ": "添加到技能条目：",
  "Already there: ": "已有内容：",
  "Your facts show it, but this CV leaves it out": "事实资料中有依据，但本简历未体现",
  "Related only": "仅有关联",
  "No evidence in your confirmed facts": "已确认的事实中没有依据",
  "Not checked": "未核验",
  "left out": "未体现",
  "related only": "仅有关联",
  "no evidence": "无依据",
  "not checked": "未核验",
  "cut for this job": "针对该岗位已删去",
  "reworded in a way that no longer shows it": "改写后未再体现该要求",
  "in your confirmed facts, but not on your CV": "已确认事实中有，但简历未包含",
  "Put it back": "恢复此内容",
  "Use your own wording": "使用原措辞",
  "Put it back in your own words": "恢复内容并使用原措辞",
  "not shown": "未体现",
  "Added to your facts and to this CV.": "已加入事实资料和这份简历。",
  "Not true for you — kept off your CV.": "与你的实际情况不符，未加入简历。",
  "True for me — add it": "符合实际，添加",
  "Not true": "不符合实际",
  "Skills to add, separated by commas": "要添加的技能，用逗号分隔",
  "The line as it should read on your CV": "输入你希望写入简历的原文",
  "Add to my CV": "添加到简历",
  "Edit it, or write your own": "修改建议，或自己填写",
  "Write your own line": "自行填写",
  "Only what is true for you. It is added as you write it, as a confirmed fact, and the CV is prepared again.": "请只填写真实情况。内容会按原文保存为已确认事实，然后重新准备简历。",
  "DeepSeek gave no usable answer for this requirement, so it does not count as shown. Use Check again.": "DeepSeek 未提供可用的核验结果，因此该要求不计为已体现。可点击“重新核验”。",
  "Check again": "重新核验",
  "Check now": "开始核验",
  "3. What this CV shows for each requirement": "3. 简历对各项要求的体现情况",
  "DeepSeek compares each requirement with your confirmed facts and with this CV as it is shown now, after cuts and rewording. ": "DeepSeek 会将每项要求与已确认事实、以及当前删减和改写后的简历进行对照。",
  "A line that is only about the same thing does not count as showing it. Nothing is added until you click True for me; ": "仅涉及相同主题的内容不算有效依据。只有点击“符合实际，添加”后才会添加内容，",
  "then it becomes a confirmed fact and the CV is prepared again.": "将其保存为已确认事实，并重新准备简历。",
  "Checking…": "核验中…",
  "Your CV or facts changed since this check. Checking again…": "上次核验后，简历或事实已变化。正在重新核验…",
  "Nothing counts as shown until it is checked. Use Check again.": "完成核验前，不计为已体现。请点击“重新核验”。",
  "This CV shows something for every requirement.": "这份简历对每项要求都有所体现。",
  "The workbench stopped in the middle of a change to this job and could not tell which one, so it left the files as they were. ": "工作台在修改该岗位时中断，无法识别具体操作，文件已保持原样。",
  "If the requirements or your CV look wrong, save the requirements again or use Start over.": "若岗位要求或简历显示异常，请重新保存要求，或点击“重新开始”。",
  "approving your CV": "批准简历",
  "creating the final PDF": "生成最终 PDF",
  "preparing your CV": "准备简历",
  "checking what your CV shows for each requirement": "核验简历对各项要求的体现情况",
  "finding talking points": "查找匹配依据",
  "saving this job's requirements": "保存岗位要求",
  "Saving an uploaded CV did not finish. Some of its lines may already be here, waiting for confirmation, and ": "上传简历的保存操作未完成。部分内容可能已在此等待确认，",
  "your CV layout may still be the old one. Upload the same PDF again and save: lines already saved are reused, ": "简历结构可能仍是旧版本。请重新上传同一 PDF 并保存，已保存的条目会直接复用，",
  "never added twice.": "不会重复添加。",
  "to add it, add it again with the same words: it will not be added twice. If it says the line was added, ": "仍可添加，请以相同文字再次添加，系统不会重复保存。如果显示已经添加，",
  "prepare the CV again so the CV shows it.": "请重新准备简历，使其包含该内容。",
  "A change did not finish, and its record could not be read. Check your facts and your CV, and repeat what ": "一项修改未完成，且无法读取记录。请核对事实资料和简历，再次执行",
  "you were doing.": "之前的操作。",
  "Prepare the CV again": "重新准备简历",
  "Dismiss": "知道了",
  "Company unknown": "公司未知",
  " · captured ": " · 录入于 ",
  "Source: unknown": "来源：未知",
  "Job description": "岗位描述",
  "2. What was found: {0} lines": "2. 识别到 {0} 行内容",
  "; {0} already match facts you have.": "；其中 {0} 行与已有事实一致。",
  "Saved your CV. All {0} lines match facts you already had.": "简历已保存。全部 {0} 行均与已有事实一致。",
  "Saved your CV. {0} new line(s) wait below for you to confirm{1}": "简历已保存。下方有 {0} 条新事实待确认{1}",
  "; {0} matched facts you already had.": "；另有 {0} 行与已有事实一致。",
  "Reading {0}…": "正在读取 {0}…",
  "Confirm {0} selected": "确认所选的 {0} 条事实",
  "Confirmed {0} fact(s).": "已确认 {0} 条事实。",
  "Confirmed {0} fact(s). These are the jobs that mention your skills.": "已确认 {0} 条事实。以下岗位提到了你的技能。",
  "{0} facts, {1} pending. Only confirmed facts can be matched or used in a CV. ": "共 {0} 条事实，{1} 条待确认。只有已确认的事实可用于匹配或简历。",
  "{0} min ago": "{0} 分钟前",
  "{0} h ago": "{0} 小时前",
  "{0} days ago": "{0} 天前",
  "{0} +{1} more": "{0}，另有 {1} 个地点",
  "posted {0}": "发布于 {0}",
  "{0} roles from {1} companies · updated {2}": "{1} 家公司，共 {0} 个岗位 · 更新于 {2}",
  "Show more ({0} left)": "显示更多（还剩 {0} 条）",
  "Following {0}: {1} open jobs.": "已关注 {0}：有 {1} 个在招岗位。",
  "Stop following {0}? Its downloaded jobs are removed from this list.": "取消关注 {0}？已获取的岗位将从此列表移除。",
  "Last try failed: {0}": "上次更新失败：{0}",
  "Companies you follow ({0})": "关注的公司（{0}）",
  "Downloading jobs… {0} of {1} companies": "正在获取岗位… 已完成 {0}/{1} 家公司",
  "{0} company(ies) could not be updated. Details are under Companies.": "{0} 家公司更新失败，详情见公司列表。",
  "Saved: {0} requirement(s). The CV was prepared again for them.": "已保存 {0} 项要求，并据此重新准备了简历。",
  "Found by heading rules{0}.": "根据标题规则提取{0}。",
  " (DeepSeek not used: {0})": "（未使用 DeepSeek：{0}）",
  "{0} requirement(s){1} — open to review or change": "共 {0} 项要求{1}，展开可审核或修改",
  ", {0} counted automatically and not reviewed by you": "，其中 {0} 项自动计入，尚未经你审核",
  "Approved {0}. To change anything, use Start over and approve again.": "已于 {0} 批准。如需修改，请点击“重新开始”并重新审核批准。",
  "Shown in the other language because your profile has no {0} text for — ": "以下内容缺少{0}版本，因此显示另一语言原文：",
  "{0} change(s) from your usual CV": "相较原简历有 {0} 处修改",
  "{0} rewording(s) failed the fact check, so your own wording is kept": "{0} 处改写未通过事实核查，已保留原措辞",
  "{0} preview": "{0}预览",
  "{0} for this job": "为此岗位准备的{0}",
  "New line under {0}: ": "在“{0}”下新增：",
  "New line under {0}": "在“{0}”下新增",
  "Add to skills line: {0}": "添加到技能条目：{0}",
  "Not checked: {0} ": "未核验：{0} ",
  "No suggestions this time: {0} Use Check again.": "本次未生成建议：{0}。可点击“重新核验”。",
  "Shown in this CV ({0})": "本简历已体现（{0}）",
  "The workbench stopped while {0}, so that change was undone and nothing half-done was kept. Do it again if you still want it.": "工作台在{0}时中断，已撤销该次修改，没有保留未完成的结果。如仍需要，请重新操作。",
  "Adding “{0}” for “{1}” did not finish. If that requirement below still offers ": "为“{1}”添加“{0}”的操作未完成。如果下方该要求",
  "confirmed": "已确认",
  "pending": "待确认",
  "shown": "已体现",
  "education": "教育",
  "experience": "经历",
  "project": "项目",
  "skill": "技能",
  "other": "其他",
  "{0} line(s) not imported": "{0} 行未导入",
  "Built from your confirmed facts.": "已根据确认的事实生成。",
  "Reworded for this job: {0} line(s) changed{1}.": "已针对岗位润色：修改 {0} 行{1}。",
  "; {0} kept as confirmed because the rewording failed the fact check": "；{0} 行改写未通过事实核查，已保留确认过的原文",
  "Adjusted for this job: {0} change(s), listed below.": "已针对岗位调整，共 {0} 处修改，详见下方。",
  "Adjusted for this job: your usual layout already fits.": "已完成针对岗位的检查，原有结构已适合。",
  "Not prepared": "未能生成草稿",
  "Not reworded": "未能润色",
  "Not adjusted for this job": "未能完成岗位调整",
  "{0} again: {1}": "再次{0}：{1}",
  "{0}: {1}": "{0}：{1}",
  "Your confirmed wording is used.": "已使用确认过的原文。",
  "Your usual layout is used.": "已使用原有结构。",
  "The earlier rewording below is kept.": "保留下方上一次的润色结果。",
  "The earlier adjusted layout below is kept.": "保留下方上一次的结构调整结果。",
  " since the last change; use the button below.": "，上次修改后尚未完成，请使用下方按钮重试。",
  ": the CV could not be drafted.": "：尚未生成简历草稿。",
  "This CV changed after the page showed it (another tab or window changed it). Read it again below, then approve.": "页面显示后，简历已被其他标签页或窗口修改。请重新阅读下方的当前版本，再进行批准。",
  "No DeepSeek API key was found. Add it to the Keychain (service deepseek-api-key), set DEEPSEEK_API_KEY, or on a server put it in the file DEEPSEEK_API_KEY_FILE names (on AWS: the Secrets Manager secret the stack names), then try again.": "未找到 DeepSeek API key。请将密钥存入本机钥匙串的 deepseek-api-key 项；服务器需配置密钥文件，AWS 需配置 Secrets Manager，然后重试。",
  "DeepSeek refused the API key. Check or replace the key, then try again.": "DeepSeek 拒绝了该 API key，请核对或更换密钥后重试。",
  "DeepSeek is busy right now. Try again in a minute.": "DeepSeek 当前繁忙，请稍后重试。",
  "DeepSeek could not be reached. Check the internet connection, then try again.": "无法连接 DeepSeek，请检查网络后重试。",
  "DeepSeek returned an error. Try again later.": "DeepSeek 返回错误，请稍后重试。",
  "DeepSeek's answer could not be used. Try again.": "DeepSeek 的回复无法使用，请重试。",
  "DeepSeek found no requirement lines.": "DeepSeek 未找到岗位要求。",
  "There is no CV yet. Upload your CV on the Facts page.": "还没有简历，请在“事实资料”页面上传。",
  "There are no facts yet. Upload your CV on the Facts page.": "还没有事实资料，请在“事实资料”页面上传简历。",
  "Some lines of your CV are not confirmed yet. Confirm them on the Facts page.": "部分简历内容尚未确认，请在“事实资料”页面确认。",
  "Your CV lists facts that are no longer stored. Upload your CV again on the Facts page.": "简历引用的部分事实已不存在，请在“事实资料”页面重新上传简历。",
  "Your CV layout file could not be read, so it is not clear what must stay private. Nothing was sent to DeepSeek. Upload your CV again on the Facts page.": "无法读取简历结构文件，因此无法确定哪些信息必须保密。未向 DeepSeek 发送任何内容，请在“事实资料”页面重新上传简历。",
  "A backup of your CV layout ({file} in .local/profile-history) could not be read, so it is not clear what must stay private. Nothing was sent to DeepSeek. Delete or fix that file, then try again.": "无法读取简历结构备份（.local/profile-history 中的 {file}），因此无法确定哪些信息必须保密。未向 DeepSeek 发送任何内容，请修复或删除该文件后重试。",
  "Missing: {0}": "缺少：{0}",
  "eligibility": "资格",
  "availability": "可到岗时间",
  "achievement": "成果",
  " The CV below is from the last time it could be prepared.": " 下方简历来自上一次成功生成的结果。"
};
